### ISSUE TITLE
pykinect2

### ISSUE THREAD

**Issue by Zoey6677** [KonstantinosAng/PyKinect2-PyQtGraph-PointClouds#9]
Traceback (most recent call last):
  File "D:\Software\PyCharm2023\PycharmProjects\PyKinect2-PyQtGraph-PointClouds-master\PointCloud.py", line 11, in <module>
    from pykinect2.PyKinectV2 import *
  File "D:\Software\anaconda3\envs\py36\lib\site-packages\pykinect2\PyKinectV2.py", line 2216, in <module>
    assert sizeof(tagSTATSTG) == 72, sizeof(tagSTATSTG)
AssertionError: 80

**Comment by KonstantinosAng** [comment]
Check these issues from the official PyKinect2:

https://github.com/Kinect/PyKinect2/issues/17

https://github.com/Kinect/PyKinect2/issues/37
